course = 0;  // the direction a piece should face when resting on this space
nest = false;  // the space in in a nest
start = false;  // the space is a start space
safe = false;  // the space is a safe space
home = false;  // the space is in the home row
finish = false;  // the space is in the finish arrowhead
occupants = 0;  // the number of occupants in the space
blockade = false;  // the occupants of the space have formed a blockade
occupantsTeam = 0 ;